os:
  - osx
  - linux

language: c

sudo: required

compiler: gcc

before_install:
  - sudo brew update || sudo apt-get update
  - sudo brew install valgrind || sudo apt-get install -y valgrind

install:
  - ./setup.sh

before_script:
  - ./check_makefile.sh

script:
  - ./unittesting.sh

after_script:
  - ./check_makefile.sh